### ISSUE TITLE
Requst for multiple mail accounts / inboxes

### ISSUE THREAD

**Issue by pnewbery** [therecluse26/outlook-for-linux#1]
Hi there, I was overjoyed to find this Linux version of what I consider to be the best mail client out there and it appears to be an excellent implementation of it, however, it really does need to be able to manage more that one mail account for it to be pretty much perfect. 
I suspect this may be in plan already, but if not, please can it be?

**Comment by therecluse26** [comment]
My LICENSE and README.md files appear to you to be an excellent implementation of Outlook?
